# Test package every time

name: Build

# Controls when the action will run.

# Trigger this code when a new release is published
on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install python dependencies
        uses: py-actions/py-dependency-install@v2
      - name: Install utilix
        run: python setup.py install
      - name: Install pytest and hypothesis
        run: pip install pytest hypothesis flake8 pytest-cov
      - name: Test package
        # Could add more but perhaps we need to consider what we want to test first
        run: |
         python -m unittest tests/test_import.py
      - name: goodbye
        run: echo goodbye
